# SkillNexis Internship - Week 2: SQL Sales Analysis
## Topics Covered:
- **Basic Queries**: `SELECT`, `WHERE`, `ORDER BY`, `LIMIT`
- **Aggregate Functions**: `SUM`, `AVG`, `COUNT`, `MIN`, `MAX`
- **Grouping & Filtering**: `GROUP BY`, `HAVING`
- **Relational Joins**: `INNER JOIN`, `LEFT JOIN`, Multi-Table Joins
- **Subqueries**: Scalar, `WHERE IN`, and Derived Table Subqueries
- **CASE Statements**: Value Tiering & Conditional Aggregations
- **Assignments**:
  1. Top Customers Analysis (Ranked by Spending and Volume)
  2. Average Order Value (AOV) Analysis (Overall, Category, and Region)

### 1. Environment Setup & Database Connection

In [ ]:
import sqlite3
import pandas as pd

# Connect to sales.db
conn = sqlite3.connect('sales.db')

# Helper function to run and format SQL queries
def run_query(sql):
    return pd.read_sql_query(sql, conn)

print("Connected to sales.db successfully!")

### 2. Basic Queries (`SELECT`, `WHERE`, `ORDER BY`, `LIMIT`)

In [1]:
# Retrieve the first 10 sales records
query = """
SELECT order_id, customer_name, order_date, category, product_name, quantity, unit_price, total_price, region
FROM sales
LIMIT 10;
"""
run_query(query)

 order_id    customer_name order_date    category   product_name  quantity  unit_price  total_price region
     1000      Caleb Davis 2025-01-31    Clothing      Jeans Try         2        1197         2394   West
     1001    Misty Herrera 2025-05-05    Clothing      Jeans New         9        1509        13581  South
     1002        Rick Soto 2025-06-09    Clothing       Shoes Us         5        1046         5230   East
     1003        Sean Haas 2025-02-27   Furniture   Desk Section        10         292         2920  South
     1004         Ann Hall 2025-06-01   Furniture Cabinet Center         2         548         1096  North
     1005   Michelle White 2025-02-07   Furniture     Desk Point         2        2729         5458  South
     1006 Breanna Gonzalez 2025-04-09     Grocery    Bread Black         6        4356        26136   East
     1007    Angela Rivera 2025-06-18   Furniture  Chair Believe         7        2971        20797   West
     1008   Emily Anderson 2025-02-28 Electronics Mobile Evening        10         701         7010  North
     1009   Laura Anderson 2025-02-03     Grocery Snacks Capital         1        4454         4454   East

In [1]:
# Filter records for the 'West' region
query = """
SELECT order_id, customer_name, product_name, total_price, region
FROM sales
WHERE region = 'West'
LIMIT 10;
"""
run_query(query)

 order_id  customer_name    product_name  total_price region
     1000    Caleb Davis       Jeans Try         2394   West
     1007  Angela Rivera   Chair Believe        20797   West
     1011 Valerie Hooper    Couch Charge        17590   West
     1016  Rachel Wilson      Bread Skin         4826   West
     1019  Debbie Turner     Snacks Some        44990   West
     1028 Abigail Powell      Shoes Hear         2195   West
     1035 Bradley Wilson Bread Something         9054   West
     1036    John Hughes      Couch Four        13355   West
     1037  Eric Anderson     Cabinet Him         3500   West
     1039 Robert Bennett       Desk Show        13485   West

In [1]:
# Filter records with multiple conditions: Electronics with quantity >= 5
query = """
SELECT order_id, customer_name, category, product_name, quantity, total_price
FROM sales
WHERE category = 'Electronics' AND quantity >= 5;
"""
run_query(query)

 order_id       customer_name    category       product_name  quantity  total_price
     1008      Emily Anderson Electronics     Mobile Evening        10         7010
     1020         Roy Stewart Electronics      Mobile Change         5        13300
     1030    Ashley Joyce DVM Electronics    Headphones Your         9        25776
     1033           Emily Ray Electronics         Laptop Sea         6        15384
     1067         Lauren Hill Electronics       Laptop Staff         8        29192
     1069      Michele Wilson Electronics        Mobile Body         9        20880
     1074 Cassandra Wilkinson Electronics       Laptop Value         9        21879
     1087  Jennifer Alexander Electronics         Mobile All         6         8592
     1094        Brittany Ray Electronics         Tablet Get         6        19380
     1096       Daniel Torres Electronics     Tablet Contain         7        25886
     1104        Brian Butler Electronics  Headphones Should         5        17925
     1110         John Martin Electronics      Mobile Choice         8        27408
     1115         Gary Osborn Electronics        Tablet Word         9        29124
     1118       Joshua Nelson Electronics      Mobile Budget         5        13670
     1126       Zachary Jones Electronics     Laptop Concern        10        21620
     1143       Matthew Arias Electronics       Laptop Skill         7        24416
     1145       Sheila Booker Electronics    Laptop Resource         7        12817
     1153     Brandon Hoffman Electronics        Laptop Next         6        24054
     1182       Shannon Brown Electronics Headphones Receive         6        27564
     1184           Gina Bush Electronics Laptop Environment         9        31194

In [1]:
# Sort sales from highest to lowest total price
query = """
SELECT order_id, customer_name, category, total_price
FROM sales
ORDER BY total_price DESC
LIMIT 10;
"""
run_query(query)

 order_id      customer_name  category  total_price
     1125      Lynn Garrison   Grocery        47940
     1019      Debbie Turner   Grocery        44990
     1168      Megan Charles  Clothing        44620
     1160   Michelle Beltran Furniture        42471
     1120       Rick Sanford Furniture        41211
     1070     Patrick Watson Furniture        37680
     1190  Christopher Meyer   Grocery        37320
     1149        Todd Barnes Furniture        36152
     1114 Stephanie Martinez   Grocery        34576
     1174  Kimberly Alvarado Furniture        31752

### 3. Aggregate Functions (`SUM`, `AVG`, `COUNT`, `MIN`, `MAX`)

In [1]:
# Key summary metrics across all sales orders
query = """
SELECT 
    COUNT(*) AS total_orders,
    SUM(total_price) AS total_revenue,
    ROUND(AVG(total_price), 2) AS average_order_value,
    MIN(total_price) AS min_order_value,
    MAX(total_price) AS max_order_value
FROM sales;
"""
run_query(query)

 total_orders  total_revenue  average_order_value  min_order_value  max_order_value
          200        2420107             12100.53               79            47940

In [1]:
# Total units sold and unique customer/category counts
query = """
SELECT 
    SUM(quantity) AS total_units_sold,
    COUNT(DISTINCT customer_name) AS unique_customers,
    COUNT(DISTINCT category) AS unique_categories
FROM sales;
"""
run_query(query)

 total_units_sold  unique_customers  unique_categories
              982               200                  4

### 4. Grouping & Filtering (`GROUP BY`, `HAVING`)

In [1]:
# Revenue and volume summarized by product category
query = """
SELECT 
    category,
    COUNT(*) AS total_orders,
    SUM(quantity) AS total_units_sold,
    SUM(total_price) AS total_revenue,
    ROUND(AVG(total_price), 2) AS avg_order_value
FROM sales
GROUP BY category
ORDER BY total_revenue DESC;
"""
run_query(query)

   category  total_orders  total_units_sold  total_revenue  avg_order_value
  Furniture            59               269         714399         12108.46
    Grocery            49               269         672147         13717.29
Electronics            52               217         549302         10563.50
   Clothing            40               227         484259         12106.48

In [1]:
# Sales distribution by geographic region
query = """
SELECT 
    region,
    COUNT(*) AS total_orders,
    SUM(total_price) AS total_revenue,
    ROUND(AVG(total_price), 2) AS average_order_value
FROM sales
GROUP BY region
ORDER BY total_revenue DESC;
"""
run_query(query)

region  total_orders  total_revenue  average_order_value
 South            66         808651             12252.29
  East            51         619250             12142.16
  West            43         599367             13938.77
 North            40         392839              9820.98

In [1]:
# Categories with total revenue exceeding 500,000 using HAVING
query = """
SELECT 
    category,
    COUNT(*) AS order_count,
    SUM(total_price) AS total_revenue
FROM sales
GROUP BY category
HAVING SUM(total_price) > 500000
ORDER BY total_revenue DESC;
"""
run_query(query)

   category  order_count  total_revenue
  Furniture           59         714399
    Grocery           49         672147
Electronics           52         549302

### 5. Relational Joins (`INNER JOIN`, `LEFT JOIN`)

In [1]:
# INNER JOIN between Orders and Customers
query = """
SELECT 
    o.order_id,
    c.customer_name,
    c.region,
    o.order_date,
    o.total_price
FROM orders o
INNER JOIN customers c 
    ON o.customer_id = c.customer_id
ORDER BY o.total_price DESC
LIMIT 10;
"""
run_query(query)

 order_id      customer_name region order_date  total_price
     1125      Lynn Garrison   East 2025-05-14        47940
     1019      Debbie Turner   West 2025-03-22        44990
     1168      Megan Charles   West 2025-03-26        44620
     1160   Michelle Beltran   East 2025-03-23        42471
     1120       Rick Sanford  South 2025-05-12        41211
     1070     Patrick Watson   West 2025-01-07        37680
     1190  Christopher Meyer   East 2025-01-18        37320
     1149        Todd Barnes  North 2025-02-04        36152
     1114 Stephanie Martinez   West 2025-06-01        34576
     1174  Kimberly Alvarado  North 2025-04-06        31752

In [1]:
# Multi-Table INNER JOIN (Orders + Customers + Products)
query = """
SELECT 
    o.order_id,
    c.customer_name,
    c.region,
    p.category,
    p.product_name,
    o.quantity,
    p.unit_price,
    o.total_price
FROM orders o
INNER JOIN customers c 
    ON o.customer_id = c.customer_id
INNER JOIN products p 
    ON o.product_id = p.product_id
ORDER BY o.order_id ASC
LIMIT 10;
"""
run_query(query)

 order_id    customer_name region    category   product_name  quantity  unit_price  total_price
     1000      Caleb Davis   West    Clothing      Jeans Try         2        1197         2394
     1001    Misty Herrera  South    Clothing      Jeans New         9        1509        13581
     1002        Rick Soto   East    Clothing       Shoes Us         5        1046         5230
     1003        Sean Haas  South   Furniture   Desk Section        10         292         2920
     1004         Ann Hall  North   Furniture Cabinet Center         2         548         1096
     1005   Michelle White  South   Furniture     Desk Point         2        2729         5458
     1006 Breanna Gonzalez   East     Grocery    Bread Black         6        4356        26136
     1007    Angela Rivera   West   Furniture  Chair Believe         7        2971        20797
     1008   Emily Anderson  North Electronics Mobile Evening        10         701         7010
     1009   Laura Anderson   East     Grocery Snacks Capital         1        4454         4454

In [1]:
# LEFT JOIN Regional Targets with Actual Sales & Variance
query = """
SELECT 
    t.region,
    t.regional_manager,
    t.target_revenue,
    COALESCE(SUM(s.total_price), 0) AS actual_revenue,
    ROUND(COALESCE(SUM(s.total_price), 0) - t.target_revenue, 2) AS revenue_variance,
    CASE 
        WHEN COALESCE(SUM(s.total_price), 0) >= t.target_revenue THEN 'Target Achieved'
        ELSE 'Target Not Achieved'
    END AS performance_status
FROM regional_targets t
LEFT JOIN sales s 
    ON t.region = s.region
GROUP BY t.region, t.regional_manager, t.target_revenue
ORDER BY actual_revenue DESC;
"""
run_query(query)

region regional_manager  target_revenue  actual_revenue  revenue_variance  performance_status
 South     David Miller        750000.0          808651           58651.0     Target Achieved
  East    Sarah Johnson        600000.0          619250           19250.0     Target Achieved
  West    Michael Brown        550000.0          599367           49367.0     Target Achieved
 North     Emily Wilson        450000.0          392839          -57161.0 Target Not Achieved

### 6. Subqueries (Scalar, `WHERE IN`, Derived Tables)

In [1]:
# Scalar Subquery: Orders higher than overall average order value
query = """
SELECT 
    order_id,
    customer_name,
    category,
    total_price
FROM sales
WHERE total_price > (
    SELECT AVG(total_price) 
    FROM sales
)
ORDER BY total_price DESC
LIMIT 10;
"""
run_query(query)

 order_id      customer_name  category  total_price
     1125      Lynn Garrison   Grocery        47940
     1019      Debbie Turner   Grocery        44990
     1168      Megan Charles  Clothing        44620
     1160   Michelle Beltran Furniture        42471
     1120       Rick Sanford Furniture        41211
     1070     Patrick Watson Furniture        37680
     1190  Christopher Meyer   Grocery        37320
     1149        Todd Barnes Furniture        36152
     1114 Stephanie Martinez   Grocery        34576
     1174  Kimberly Alvarado Furniture        31752

In [1]:
# Multi-Row Subquery with IN: Orders from regions where AOV exceeds 12,000
query = """
SELECT 
    order_id,
    customer_name,
    region,
    total_price
FROM sales
WHERE region IN (
    SELECT region
    FROM sales
    GROUP BY region
    HAVING AVG(total_price) > 12000
)
ORDER BY total_price DESC
LIMIT 10;
"""
run_query(query)

 order_id      customer_name region  total_price
     1125      Lynn Garrison   East        47940
     1019      Debbie Turner   West        44990
     1168      Megan Charles   West        44620
     1160   Michelle Beltran   East        42471
     1120       Rick Sanford  South        41211
     1070     Patrick Watson   West        37680
     1190  Christopher Meyer   East        37320
     1114 Stephanie Martinez   West        34576
     1184          Gina Bush  South        31194
     1167        Julie Adams   East        31108

In [1]:
# Derived Table Subquery: Difference from Category Average
query = """
SELECT 
    s.order_id,
    s.customer_name,
    s.category,
    s.total_price,
    ROUND(cat_stats.category_avg, 2) AS category_avg_price,
    ROUND(s.total_price - cat_stats.category_avg, 2) AS difference_from_category_avg
FROM sales s
INNER JOIN (
    SELECT 
        category,
        AVG(total_price) AS category_avg
    FROM sales
    GROUP BY category
) cat_stats 
    ON s.category = cat_stats.category
ORDER BY difference_from_category_avg DESC
LIMIT 10;
"""
run_query(query)

 order_id      customer_name    category  total_price  category_avg_price  difference_from_category_avg
     1125      Lynn Garrison     Grocery        47940            13717.29                      34222.71
     1168      Megan Charles    Clothing        44620            12106.48                      32513.53
     1019      Debbie Turner     Grocery        44990            13717.29                      31272.71
     1160   Michelle Beltran   Furniture        42471            12108.46                      30362.54
     1120       Rick Sanford   Furniture        41211            12108.46                      29102.54
     1070     Patrick Watson   Furniture        37680            12108.46                      25571.54
     1149        Todd Barnes   Furniture        36152            12108.46                      24043.54
     1190  Christopher Meyer     Grocery        37320            13717.29                      23602.71
     1114 Stephanie Martinez     Grocery        34576            13717.29                      20858.71
     1184          Gina Bush Electronics        31194            10563.50                      20630.50

### 7. CASE Statements (Conditional Logic & Segmentation)

In [1]:
# Order Value Tiering using CASE
query = """
SELECT 
    order_id,
    customer_name,
    category,
    total_price,
    CASE 
        WHEN total_price >= 20000 THEN 'High Value (>= 20k)'
        WHEN total_price >= 10000 THEN 'Medium Value (10k-20k)'
        ELSE 'Low Value (< 10k)'
    END AS order_value_tier
FROM sales
ORDER BY total_price DESC
LIMIT 10;
"""
run_query(query)

 order_id      customer_name  category  total_price    order_value_tier
     1125      Lynn Garrison   Grocery        47940 High Value (>= 20k)
     1019      Debbie Turner   Grocery        44990 High Value (>= 20k)
     1168      Megan Charles  Clothing        44620 High Value (>= 20k)
     1160   Michelle Beltran Furniture        42471 High Value (>= 20k)
     1120       Rick Sanford Furniture        41211 High Value (>= 20k)
     1070     Patrick Watson Furniture        37680 High Value (>= 20k)
     1190  Christopher Meyer   Grocery        37320 High Value (>= 20k)
     1149        Todd Barnes Furniture        36152 High Value (>= 20k)
     1114 Stephanie Martinez   Grocery        34576 High Value (>= 20k)
     1174  Kimberly Alvarado Furniture        31752 High Value (>= 20k)

In [1]:
# Purchase Size Segmentation by Quantity
query = """
SELECT 
    order_id,
    customer_name,
    product_name,
    quantity,
    CASE 
        WHEN quantity >= 8 THEN 'Bulk Purchase'
        WHEN quantity >= 4 THEN 'Standard Purchase'
        ELSE 'Small Purchase'
    END AS purchase_size
FROM sales
ORDER BY quantity DESC
LIMIT 10;
"""
run_query(query)

 order_id    customer_name   product_name  quantity purchase_size
     1003        Sean Haas   Desk Section        10 Bulk Purchase
     1008   Emily Anderson Mobile Evening        10 Bulk Purchase
     1011   Valerie Hooper   Couch Charge        10 Bulk Purchase
     1012       Kyle Kirby  Juice Country        10 Bulk Purchase
     1019    Debbie Turner    Snacks Some        10 Bulk Purchase
     1022 Benjamin Meadows      Shoes Job        10 Bulk Purchase
     1046     Julian White   Chair Amount        10 Bulk Purchase
     1105  George Hamilton     Juice Sort        10 Bulk Purchase
     1125    Lynn Garrison    Snacks Wish        10 Bulk Purchase
     1126    Zachary Jones Laptop Concern        10 Bulk Purchase

In [1]:
# Conditional Aggregation (Category Breakdown by Region)
query = """
SELECT 
    region,
    COUNT(*) AS total_orders,
    SUM(CASE WHEN category = 'Electronics' THEN total_price ELSE 0 END) AS electronics_revenue,
    SUM(CASE WHEN category = 'Furniture' THEN total_price ELSE 0 END) AS furniture_revenue,
    SUM(CASE WHEN category = 'Grocery' THEN total_price ELSE 0 END) AS grocery_revenue,
    SUM(CASE WHEN category = 'Clothing' THEN total_price ELSE 0 END) AS clothing_revenue,
    SUM(total_price) AS total_regional_revenue
FROM sales
GROUP BY region
ORDER BY total_regional_revenue DESC;
"""
run_query(query)

region  total_orders  electronics_revenue  furniture_revenue  grocery_revenue  clothing_revenue  total_regional_revenue
 South            66               225015             191834           204318            187484                  808651
  East            51                93704             152365           226818            146363                  619250
  West            43               123423             178610           177697            119637                  599367
 North            40               107160             191590            63314             30775                  392839

### 8. Assignments: Top Customers & Average Order Values

In [1]:
# Assignment 1.1: Top 10 Customers by Total Spending
query = """
SELECT 
    customer_name,
    region,
    COUNT(*) AS number_of_orders,
    SUM(quantity) AS total_units_purchased,
    SUM(total_price) AS total_spending,
    ROUND(AVG(total_price), 2) AS average_order_value
FROM sales
GROUP BY customer_name, region
ORDER BY total_spending DESC
LIMIT 10;
"""
run_query(query)

     customer_name region  number_of_orders  total_units_purchased  total_spending  average_order_value
     Lynn Garrison   East                 1                     10           47940              47940.0
     Debbie Turner   West                 1                     10           44990              44990.0
     Megan Charles   West                 1                     10           44620              44620.0
  Michelle Beltran   East                 1                      9           42471              42471.0
      Rick Sanford  South                 1                      9           41211              41211.0
    Patrick Watson   West                 1                      8           37680              37680.0
 Christopher Meyer   East                 1                      8           37320              37320.0
       Todd Barnes  North                 1                      8           36152              36152.0
Stephanie Martinez   West                 1                      8           34576              34576.0
 Kimberly Alvarado  North                 1                      7           31752              31752.0

In [1]:
# Assignment 1.2: Top Customer per Geographic Region
query = """
SELECT 
    s1.region,
    s1.customer_name,
    s1.total_price AS highest_single_order_value
FROM sales s1
WHERE s1.total_price = (
    SELECT MAX(s2.total_price)
    FROM sales s2
    WHERE s2.region = s1.region
)
ORDER BY s1.total_price DESC;
"""
run_query(query)

region customer_name  highest_single_order_value
  East Lynn Garrison                       47940
  West Debbie Turner                       44990
 South  Rick Sanford                       41211
 North   Todd Barnes                       36152

In [1]:
# Assignment 2.1: Overall Store Average Order Value (AOV)
query = """
SELECT 
    COUNT(*) AS total_orders,
    SUM(total_price) AS total_revenue,
    ROUND(AVG(total_price), 2) AS overall_average_order_value
FROM sales;
"""
run_query(query)

 total_orders  total_revenue  overall_average_order_value
          200        2420107                     12100.53

In [1]:
# Assignment 2.2: Average Order Value (AOV) by Product Category
query = """
SELECT 
    category,
    COUNT(*) AS orders_count,
    SUM(total_price) AS total_revenue,
    ROUND(AVG(total_price), 2) AS average_order_value
FROM sales
GROUP BY category
ORDER BY average_order_value DESC;
"""
run_query(query)

   category  orders_count  total_revenue  average_order_value
    Grocery            49         672147             13717.29
  Furniture            59         714399             12108.46
   Clothing            40         484259             12106.48
Electronics            52         549302             10563.50

In [1]:
# Assignment 2.3: Average Order Value (AOV) by Geographic Region
query = """
SELECT 
    region,
    COUNT(*) AS orders_count,
    SUM(total_price) AS total_revenue,
    ROUND(AVG(total_price), 2) AS average_order_value
FROM sales
GROUP BY region
ORDER BY average_order_value DESC;
"""
run_query(query)

region  orders_count  total_revenue  average_order_value
  West            43         599367             13938.77
 South            66         808651             12252.29
  East            51         619250             12142.16
 North            40         392839              9820.98

In [1]:
# Assignment 2.4: Orders Exceeding Average Order Value
query = """
SELECT 
    order_id,
    customer_name,
    category,
    total_price,
    ROUND((SELECT AVG(total_price) FROM sales), 2) AS overall_avg,
    ROUND(total_price - (SELECT AVG(total_price) FROM sales), 2) AS amount_above_avg,
    ROUND(((total_price - (SELECT AVG(total_price) FROM sales)) / (SELECT AVG(total_price) FROM sales)) * 100, 2) AS pct_above_avg
FROM sales
WHERE total_price > (SELECT AVG(total_price) FROM sales)
ORDER BY total_price DESC
LIMIT 10;
"""
run_query(query)

 order_id      customer_name  category  total_price  overall_avg  amount_above_avg  pct_above_avg
     1125      Lynn Garrison   Grocery        47940     12100.53          35839.46         296.18
     1019      Debbie Turner   Grocery        44990     12100.53          32889.46         271.80
     1168      Megan Charles  Clothing        44620     12100.53          32519.47         268.74
     1160   Michelle Beltran Furniture        42471     12100.53          30370.47         250.98
     1120       Rick Sanford Furniture        41211     12100.53          29110.47         240.57
     1070     Patrick Watson Furniture        37680     12100.53          25579.47         211.39
     1190  Christopher Meyer   Grocery        37320     12100.53          25219.47         208.42
     1149        Todd Barnes Furniture        36152     12100.53          24051.47         198.76
     1114 Stephanie Martinez   Grocery        34576     12100.53          22475.47         185.74
     1174  Kimberly Alvarado Furniture        31752     12100.53          19651.47         162.40